---
title: US Unprepared for Next Pandemic, Says Government Watchdog
author: admin
date: '2022-01-28'
slug: us-unprepared-for-next-pandemic-says-government-watchdog
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: ''
featured: no
image:
  caption: 'Image credit: [**Markus Spiske**](https://www.pexels.com/@markusspiske)'
  placement: 3
  focal_point: ''
  preview_only: no
projects: []
---

**The non-partisan Government Accountability Office (GAO) has this week added the US Department of Health and Human Services’ (HHS) leadership and coordination of public health emergencies to its “high risk list”.**

In its accompanying [report](https://www.gao.gov/assets/gao-22-105291.pdf), GAO claims that there have been persistent deficiencies in HHS’ ability to prepare for, and respond to, public health emergencies, citing the department's response to the current COVID-19 pandemic and a number of past threats, including the H1N1 influenza pandemic, Zika, Ebola, and extreme weather events, such as hurricanes.

Moreover, GAO claims that *"if left unaddressed, these deficiencies will continue to hamper the nation’s ability to be prepared for, and effectively respond to, future threats"*.

{{% callout note %}}
GAO’s “High Risk List”, which is issued every two years at the start of each new session of Congress, lists federal programs and operations that are deemed by the GAO vulnerable to fraud, waste, abuse, and mismanagement, or need transformation.
{{% /callout %}}


The report singles out the role of particular agencies and offices, including: 

* the **Office of the Assistant Secretary for Preparedness and Response (ASPR)**, which serves as the principal advisor to the Secretary of Health and Human Services on all matters related to federal public health and medical preparedness and response to public health emergencies; <br><br>

* the **Centers for Disease Control and Prevention (CDC)**, which supports public health supports public health preparedness efforts to prevent, detect, and respond to new and emerging disease threats; and <br><br>

* the **Food and Drug Administration (FDA)**, which plays a critical role in protecting the U.S. from biological threats, including intentional acts and naturally occurring infectious diseases. For example, FDA is responsible for ensuring that medical countermeasures—including drugs, vaccines, diagnostic tests, and personal protective equipment—against these threats are safe and effective.

## **Existing failings**


Discussing HHS’ track record, the report takes note of the following failings:

##### *Decision-making roles for national biodefense resources*

GAO claims that HHS has thus far failed to adequately document decision-making roles among members of the Biodefense Steering Committee and Coordination Team (the body which facilitates joint decision-making for the National Biodefense Strategy). In a previous report, published in February 2020, GAO reported that there that there were no clear, detailed processes, roles, and responsibilities for joint decision-making among the Biodefense Steering Committee and Coordination Team, and that HHS officials reported being unsure how decisions related to prioritizing and allocating national biodefense resources would be made. This, GAO suggests, has the potential to *“impede the ability of agencies to address gaps or leverage resources that span department and agency boundaries, which is frequently the situation for biodefense”*.

##### *HHS agencies’ roles and responsibilities in repatriating US citizens during the COVID-19 pandemic*

Similarly, the report notes that while repatriating US citizens during the earlier stages of the COVID-19 pandemic, HHS put repatriates, its own personnel, and nearby communities at risk due to a lack of clarity as to which HHS agency was in charge, including which HHS agency was responsible for managing infection prevention. GAO suggests that this led to fundamental led to problems including a delay in issuing a federal quarantine order, during which time a repatriate tried to leave the quarantine facility; inconsistent use of personal protective equipment to protect HHS responders from the virus; and ASPR allowing asymptomatic COVID-19 positive repatriates to return on flights with citizens who had not tested positive, contradicting CDC guidance. GAO claims that HHS has not yet fully addressed GAO’s recommendations to revise or develop new plans that clarify agency roles and responsibilities during a pandemic, and regularly exercise these plans with key partners.

##### *HHS’s role in medical countermeasure management*

GAO also note the continued shortage of effective medical countermeasures, which include vaccines, drugs, diagnostics, and related supplies, such as PPE. The report claims that the current pandemic has highlighted gaps in clearly defined roles and responsibilities for the management of critical supplies, including the Strategic National Stockpile (SNS). GAO also states that, despite previous recommendations, HHS has thus far failed to work with the Federal Emergency Management Agency (FEMA) to outline specific actions the federal government will take to help mitigate supply chain shortages for the remainder of the pandemic. 

##### *Collection and analysis of data to inform decision-making and future preparedness*

The report also highlights the incomplete and inconsistent nature of data that HHS have relied upon during the COVID-19 pandemic. For example, GAO suggests that the interpretation of testing, case count, and hospital capacity data has proven challenging because the data HHS collects are often incomplete and inconsistent. Similarly, they claim that persistent gaps in race and ethnicity data have limited the nation’s ability to effectively target pandemic response efforts to racial and ethnic groups that available data suggest may be disproportionately affected.

##### *Clarity and consistency of communication to key partners and the public*

GAO’s assessment of the HHS’ ability communicate effectively with key stakeholders is particularly damning. GAO claims that, during critical incidents, HHS has often provided unclear and inconsistent communications. For example, the report notes that some stakeholders said states often did not have information critical to COVID-19 distribution at the local level, such as how many doses they would receive and when. Similarly, GAO states that there has also been inconsistent communication to health care providers about the use of certain PPE – specifically citing the inconsistent information on the recommended use of decontamination systems for respirators between FDA and CDC, which, they suggest, led to some confusion and hesitancy among providers about using such devices. GAO also claims that HHS has failed to issue a publicly available and comprehensive national testing strategy, which has lead to the public lacking crucial information to support an informed and coordinated testing response.

## **Recommendations going forward**

Going forward, GAO suggests that HHS should implement the following recommendations: 

* **Implement clearly defined roles and responsibilities**. HHS should direct the Biodefense Coordination Team to document agreed upon processes, roles, and responsibilities for making and enforcing joint decisions across federal agencies and their partners involved in protecting the nation against catastrophic biological threats.

* **Start collecting complete and consistent data**. HHS should establish the nationwide public health situational awareness network capability to help ensure timely and complete collection of public health data to aid a response, and use an expert committee to systematically review, and help standardize, the ongoing collection and reporting of public health data.

* **Provide clear and consistent communication**. FDA and CDC should develop a process to ensure consistent guidance for health care providers on the appropriate use of personal protective equipment during future public health emergencies. 

* **Provide more transparency and accountability**. ASPR should develop plans to ensure a transparent and deliberative process for making recommendations on the procurement of vaccines, supplies, and other materials for the SNS and maintain related documentation, including the rationale and outcomes for decisions made. 

* **Understanding key partners’ capabilities and limitations**. ASPR should work with key federal response partners to develop and finalize memorandums of agreement that include information on the capabilities and limitations of these agencies to meet public health and medical services core capabilities during public health emergencies.

The full report can be found [here](https://www.gao.gov/assets/gao-22-105291.pdf).

